import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
        padding: '0.5in',
        fontFamily: 'Times-Roman',
        color: '#111827',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: '#111827',
        paddingBottom: 20,
        marginBottom: 20,
    },
    photoContainer: {
        width: 90,
        height: 90,
        borderRadius: 45,
        marginRight: 25,
        borderWidth: 2,
        borderColor: '#111827',
        overflow: 'hidden',
    },
    photo: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
    },
    headerRight: {
        flex: 1,
        justifyContent: 'center',
    },
    name: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#111827',
    },
    contactInfo: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 15,
        fontSize: 10.5,
        color: '#374151',
        fontWeight: 'bold',
    },
    links: {
        color: '#2563eb',
        textDecoration: 'none',
        fontWeight: 'bold',
    },
    section: {
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#111827',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginTop: 18,
        marginBottom: 8,
    },
    description: {
        fontSize: 10.5,
        color: '#374151',
        textAlign: 'justify',
        lineHeight: 1.6,
        marginVertical: 5,
    },
    skillsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 5,
        marginBottom: 5,
    },
    skillTag: {
        backgroundColor: '#f3f4f6',
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 6,
        fontSize: 10,
        fontWeight: 'bold',
        borderWidth: 1,
        borderColor: '#d1d5db',
        color: '#111827',
    },
    itemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        marginBottom: 3,
    },
    itemTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#111827',
    },
    itemDuration: {
        fontSize: 10,
        color: '#6b7280',
        fontWeight: 'bold',
    },
    itemSub: {
        fontSize: 10.5,
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#4b5563',
        marginBottom: 4,
    },
    projectLink: {
        fontSize: 9.5,
        color: '#2563eb',
        fontWeight: 'bold',
        textDecoration: 'none',
        backgroundColor: '#eff6ff',
        paddingVertical: 2,
        paddingHorizontal: 6,
        borderRadius: 4,
    }
});
